# Ahora se vincula al listener "https" del Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ruta-para-kite
  namespace: kube-system
spec:
  parentRefs: 
  - name: gateway-principal
    namespace: nginx-gateway
    sectionName: https
  
  hostnames:
  - "kiteazure.chicho.com.ar"
  
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: kite
      port: 8080